# Generated by Django 4.2.5 on 2023-09-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_leaning_product_users_delete_choice_delete_question'),
    ]

    operations = [
    ]
