# Generated by Django 4.2.5 on 2023-09-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230921_0219'),
    ]

    operations = [
    ]
