# Generated by Django 4.2.5 on 2023-09-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230921_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('values', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ownder',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_leaning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.leaning'),
        ),
    ]
