# Generated by Django 4.2.5 on 2023-09-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_delete_users_rename_ownder_product_name_and_more'),
    ]

    operations = [
    ]
