# Generated by Django 4.2.5 on 2023-09-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_id_leaning'),
    ]

    operations = [
    ]
