# Generated by Django 4.2.5 on 2023-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20230923_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_leaning',
            new_name='name_leaning',
        ),
    ]
