# Generated by Django 4.2.5 on 2023-09-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_id_leaning_product_name_leaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_leaning',
        ),
    ]
