# Generated by Django 4.2.5 on 2023-09-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_product_name_leaning'),
    ]

    operations = [
    ]
