# Generated by Django 4.2.5 on 2023-09-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230923_1904'),
    ]

    operations = [
    ]
